- name: Create Windows VM on OpenShift
  become: false
  hosts: localhost
  roles:
    - role: winvm

- name: Wait For Connection and Change Administrator Password
  become: false
  gather_facts: false
  hosts: provisioning
  tasks:
    - name: Wait for VM
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 900

    # WinRM is deployed moments before the setup module runs. Sometimes an additional
    # attempt is required while WinRM settles.

    - name: Gather Facts
      ansible.builtin.setup:
        gather_subset:
          - all
      delay: 5
      register: setup_results
      retries: 5
      until:
        - not setup_results.failed

    - name: Change Administrator Password
      block:
        - name: Set Password
          ansible.windows.win_user:
            name: Administrator
            password: "{{ winvm_admin_password }}"
      rescue:
        - name: Update Password in Inventory
          ansible.builtin.set_fact:
            ansible_password: "{{ winvm_admin_password }}"

        - name: Test Updated Credentials
          ansible.windows.win_ping:

    - name: Configure Remote Desktop Access
      ansible.builtin.include_role:
        name: windows-enable-rdp

    - name: Join Domain
      microsoft.ad.membership:
        dns_domain_name: "{{ winvm_ad_domain }}"
        domain_admin_password: "{{ winvm_ad_admin_password }}"
        domain_admin_user: "{{ winvm_ad_admin_user }}"
        domain_server: "{{ winvm_ad_domain_server }}"
        state: domain
        reboot: true

    - name: Configure Additional Disks
      ansible.builtin.include_role:
        name: windows-setup-disks
