- name: Create IMI For VM
  become: false
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Add Domain Controller to IM Inventory
      ansible.builtin.add_host:
        ansible_connection: winrm
        ansible_user: Administrator
        ansible_password: "{{ winvm_ad_admin_password }}"
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5986
        groups: domain_controller
        name: "{{ winvm_ad_domain_server }}"

- name: Remove VM from Active Directory
  become: false
  gather_facts: false
  hosts: domain_controller
  tasks:
    - name: Remove Computer Account from Active Directory
      microsoft.ad.computer:
        domain_password: "{{ winvm_ad_admin_password }}"
        domain_server: "{{ winvm_ad_domain_server }}"
        domain_username: "{{ winvm_ad_admin_user }}"
        name: "{{ winvm_name | upper }}"
        state: absent

- name: Delete VM From OpenShift
  become: false
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Force VM Shutdown
      vars:
        vm_power_state:
          force: true
          name: "{{ winvm_name }}"
          namespace: "{{ winvm_namespace }}"
          running: false
          run_strategy: Halted
      ansible.builtin.include_role:
        name: kubevirt-vm-power-state

    - name: Delete VM
      kubevirt.core.kubevirt_vm:
        name: "{{ winvm_name | lower }}"
        namespace: "{{ winvm_namespace }}"
        state: absent

    - name: Delete ConfigMap (unattend.xml)
      kubernetes.core.k8s:
        api_version: v1
        kind: ConfigMap
        name: "sysprep-{{ winvm_name | lower }}"
        namespace: "{{ winvm_namespace }}"
        state: absent
