---
additional_build_files:
  - dest: configs
    src: ../ansible.cfg
additional_build_steps:
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  exclude:
    system:
      - openshift-clients
  galaxy: ../collections/requirements.yaml
  python:
    - dnspython
    - jmespath
    - kubernetes
    - netaddr
    - pywinrm
    - yamale
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  system: bindep.txt
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
options:
  package_manager_path: /usr/bin/microdnf
version: 3
